### PR TITLE
Add not-found.js in ./src/app

### PR DESCRIPTION
**Pull request by JanaganSaravanan**
Added a not-found.js file in app directory.

### CODE REVIEW

**Comment by JanaganSaravanan** [comment]
Sure!. I am happy to make another PR.

**Comment by JanaganSaravanan** [comment]
I have some doubts about styling not-fount.tsx file. Should i style the file internally ? I tried to run this scrum-board but i only displays some nav bar and nothing on the webpage. Can I ask you is this the case ?.

**Comment by anicmarko9** [comment]
Yes, that's the case. Here is the website in production so you can try to log in - log out and test it: [website](https://scrum-board-app.vercel.app/).

You can create NotFound.tsx file however you like, but if you don't know to route it with Next.js 13, it's okay, I'll take care of that.

@JanaganSaravanan

**Comment by anicmarko9** [comment]
I don't have a lot of free time to add things to this website, so it's pretty much empty. Only Google and GitHub authentication works, you can try those two.

**Comment by JanaganSaravanan** [comment]
Thank you for the information. I have added styling to not-found.tsx file using tailwindcss. Let me know if any modifications required.

**Comment by anicmarko9** [comment]
You need to make a pull request, otherwise I can't see anything you've done.

**Pull request closed without merging**
